name: Daily Cafe Auto Comment

on:
  schedule:
    - cron: "0 0,3,4,5,6,7,8 * * *"  # 하루에 세 번: 00:00, 04:00, 08:00 UTC 한국타임기준 09:00, 13:00, 17:00
  workflow_dispatch: {}   # 수동 실행도 가능

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_PW: ${{ secrets.NAVER_PW }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-4o-mini' }}
          TARGET_COMMUNITY: "결혼준비 토론방"
          TARGET_COUNT: "10"
          PER_PAGE_CAP: "50"
          MAX_PAGES: "20"
          DO_COMMENT: "true"
          DO_LIKE: "true"   # 원하면 true
        run: |
          python runner.py
